import React from "react"
import styles from "./pricing.module.css"

export const metadata = {
    title: "Arthur Jenck – PRICING",
    description: "Generated by create next app",
}

const page = () => {
    return (
        <div>
            <h1 className={styles.title}>Pricing</h1>
        </div>
    )
}

export default page
