import { Geist, Geist_Mono, Sora } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

const soraSans = Sora({
    variable: "--font-sora",
    subsets: ["latin"],
})

export const metadata = {
    title: "Arthur Jenck",
    description: "Generated by create next app",
    openGraph: {
        title: "Arthur Jenck",
        description: "Mon site",
    },
}

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body
                className={`${soraSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased p-20`}
            >
                {children}
            </body>
        </html>
    )
}
